lib: [
  "_build/install/default/lib/ECC/META"
  "_build/install/default/lib/ECC/dune-package"
  "_build/install/default/lib/ECC/ecc.a"
  "_build/install/default/lib/ECC/ecc.cma"
  "_build/install/default/lib/ECC/ecc.cmi"
  "_build/install/default/lib/ECC/ecc.cmt"
  "_build/install/default/lib/ECC/ecc.cmti"
  "_build/install/default/lib/ECC/ecc.cmx"
  "_build/install/default/lib/ECC/ecc.cmxa"
  "_build/install/default/lib/ECC/ecc.ml"
  "_build/install/default/lib/ECC/ecc.mli"
  "_build/install/default/lib/ECC/opam"
]
libexec: [
  "_build/install/default/lib/ECC/ecc.cmxs"
]
doc: [
  "_build/install/default/doc/ECC/LICENSE"
  "_build/install/default/doc/ECC/README.md"
]
